version: "3"
services:
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/fatec-game-backend
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/fatec-game-backend/
    ports:
      - "${PORT-3000}:3000"
      - "9222:9222"